# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6zIRombdob-rN7laEltP7BNr3_NaAUW
"""

def assembly_to_binary_r(opcode, rs, rt, rd, shamt, funct):
    #Aque le señalo al programa cuantos bits tendra cada variable
    bin_opcode = format(opcode, '06b')
    bin_rs     = format(rs, '05b')
    bin_rt     = format(rt, '05b')
    bin_rd     = format(rd, '05b')
    bin_shamt  = format(shamt, '05b')
    bin_funct  = format(funct, '06b')

    # Une todas las variables en una sola cadena de 32 bits
    binary_32bit = bin_opcode + bin_rs + bin_rt + bin_rd + bin_shamt + bin_funct

    # en esta parte basuicamente lo que hacemos es crear una variable para la lectura visual
    readable_bin = f"{bin_opcode} {bin_rs} {bin_rt} {bin_rd} {bin_shamt} {bin_funct}"
    #
    return binary_32bit, readable_bin

# Usare como ejemplo: Operación ADD (Suma)
# Estructura: add $rd, $rs, $rt -> add $1, $2, $3
op_code = 0   # Tipo R siempre es 000000
reg_rs  = 2   # Registro fuente 1 ($2)
reg_rt  = 3   # Registro fuente 2 ($3)
reg_rd  = 1   # Registro destino ($1)
shift   = 0   # No hay desplazamiento
function= 32  # El código de función (funct) para ADD es 32 (100000 en binario)

string_completo, string_separado = assembly_to_binary_r(op_code, reg_rs, reg_rt, reg_rd, shift, function)

print(f"Código binario puro (32 bits): {string_completo}")
print(f"Código binario segmentado:     {string_separado}")